{"name": "test_log02[1-1]", "status": "failed", "statusDetails": {"message": "AssertionError: assert (1 + 1) == 3", "trace": "self = <test_case.test_001.TestLogin object at 0x1058dfcd0>, a = 1, b = 1\n\n    @pytest.mark.parametrize('a,b', [(1, 1), (1, 2), (1, 3), (1, 2)])\n    def test_log02(self, a, b):\n>       assert a + b == 3\nE       assert (1 + 1) == 3\n\ntest_001.py:28: AssertionError"}, "parameters": [{"name": "a", "value": "1"}, {"name": "b", "value": "1"}], "start": 1630217495226, "stop": 1630217495227, "uuid": "7729c9c5-9d8d-4ab7-acb6-24e40b455663", "historyId": "0cb47b4299fadd954f0aa75fdc899487", "testCaseId": "6bf7f366caa83962ffb67e48ca5c6045", "fullName": "test_case.test_001.TestLogin#test_log02", "labels": [{"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_001"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "C02DV0VVMD6V"}, {"name": "thread", "value": "23156-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_001"}]}