{"name": "test_log02[1-3]", "status": "failed", "statusDetails": {"message": "AssertionError: assert (1 + 3) == 3", "trace": "self = <test_case.test_001.TestLogin object at 0x1106a9460>, a = 1, b = 3\n\n    @pytest.mark.parametrize('a,b', [(1, 1), (1, 2), (1, 3), (1, 2)])\n    def test_log02(self, a, b):\n>       assert a + b == 3\nE       assert (1 + 3) == 3\n\ntest_001.py:28: AssertionError"}, "parameters": [{"name": "a", "value": "1"}, {"name": "b", "value": "3"}], "start": 1630218942406, "stop": 1630218942406, "uuid": "aa914ea6-a512-4dad-a9e1-f77c5f3e261b", "historyId": "8d5104f02b9727de9e2a6ab89bc4839a", "testCaseId": "6bf7f366caa83962ffb67e48ca5c6045", "fullName": "test_case.test_001.TestLogin#test_log02", "labels": [{"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_001"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "C02DV0VVMD6V"}, {"name": "thread", "value": "24740-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_001"}]}